services:
  redis:
    image: redis:7
    container_name: filestorage-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:17
    container_name: filestorage-postgres
    restart: always
    environment:
      POSTGRES_DB: cloud-filestorage
      POSTGRES_USER: chuckcha
      POSTGRES_PASSWORD: chuckcha
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: