services:
  db:
    image: postgres:17
    container_name: filestorage-postgres
    restart: always
    environment:
      POSTGRES_DB: cloud-filestorage
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cloud-filestorage:
    build: .
    container_name: cloud-filestorage-container
    restart: always
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8084:8080"

volumes:
  db_data: