services:
  redis:
    image: redis:7
    container_name: filestorage-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:17
    container_name: filestorage-postgres
    restart: always
    environment:
      POSTGRES_DB: cloud-filestorage
      POSTGRES_USER: chuckcha
      POSTGRES_PASSWORD: chuckcha
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: filestorage-minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always


volumes:
  db_data:
  minio_data: