spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        batch_size: 50
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
  file:
    name: chuckcha.log
    path: /app/logs
