spring:

  datasource:
    url: jdbc:postgresql://localhost:5433/cloud-filestorage
    username: chuckcha
    password: chuckcha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        batch_size: 50
        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000