spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        batch_size: 50
        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 60000

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  root-user-directory: ${MINIO_ROOT_USER_DIRECTORY}